### ISSUE TITLE
Random Freezes

### ISSUE THREAD

**Issue by Luke100000** [JannisX11/blockbench#2000]
### What are you trying to do, and what do you expect to happen?

Editing and moving camera around.

### What happens instead?

Randomly the program freezes and recovers after a few seconds to minutes. I did not found a specific pattern yet, it appears to happen when rotation around using middle click. If it happened once, it will happen more frequently later on until restart.

While it sound similar as #1791 its not crashing, it always recovers. It affects the whole program, not just the viewport.

Memory at 180 MB, CPU btw always stuck at a full single core when visible, but I assume VSync here.

Console does not mention anything except once at startup:
```
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
APPIMAGE env is not defined, current application is not an AppImage
```

Installed `blockbench-bin` from the [AUR](https://aur.archlinux.org/packages/blockbench-bin).

I know that this is quite vague but happens quite frequent and would like to help. Are there verbosity settings or things I can try to track it further down?

### Model format in which the issue occurs

Minecraft Item

### Blockbench variant

Program

### Blockbench version

4.7.4-1 and 4.8.1-1 

### Operating System

Manjaro Arch Linux

### Installed Blockbench plugins

none

**Comment by yaetuz** [comment]
Do you use NVidia by any chance? 

Similar thing happens to me. Blockbench freezes after I open file save dialog, save the model, and then try to rotate or move the camera. It doesn't happen always, but quite often.

This is what I always see in dmesg at the moment of freezing:

`[drm:nv_drm_master_set [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000100] Failed to grab modeset ownership`

Debian 11, latest BB installed from the official deb file.

**Comment by Luke100000** [comment]
Sorry for the slow response.

Yes, you are right. I can reproduce this issue reliable by:
1. Create new model
2. Save model
3. Rotate using mouse
4. Freeze once I release mouse key

It does not happen when saving again.

However recent updates of, I assume, NVIDIA drivers caused the viewport to not render at all so now its time to just use the web app instead. Which btw works fine so far.

If I have the browser with Blockbench open as well, and the desktop app freezes, it freezes the whole browser as well.

**Comment by Luke100000** [comment]
Flatpak works btw, its a bit more painful to use and causes a set of other issues, but no more freezes.

**Comment by iam4722202468** [comment]
Also experiencing this issue

**Comment by andersmmg** [comment]
I have this issue from AUR and on the Appimage

**Comment by yaetuz** [comment]
I can no longer reproduce this bug with Blockbench 4.10.3 and nvidia-driver 535.171. Might have been fixed?

**Comment by andersmmg** [comment]
I can still reliably reproduce it with Blockbench 4.10.3 and nvidia 550.90.07

**Comment by gegentan** [comment]
Same problem with amd graphics (Ubuntu 24.04, no additional amd drivers installed)

**Comment by DragonWoven** [comment]
I can still reproduce this on 4.10.3 and nvidia 550.90.07 (Endeavor Os/Arch)

**Comment by andersmmg** [comment]
I can't reproduce it anymore so far

**Comment by Luke100000** [comment]
Same, I can no longer reproduce this on 4.12.3.
